name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        # 캐시된 이미지를 사용하여 빌드
        docker build --file Dockerfile --tag seeun0210/ahwhew-be-https:latest --cache-from seeun0210/ahwhew-be-https:latest .

        # 새로운 이미지를 빌드하여 태그를 부여하고 푸시
        docker build --file Dockerfile --tag seeun0210/ahwhew-be-https:$(date +%s) .
        docker push seeun0210/ahwhew-be-https:$(date +%s)

    - name: List Docker images
      run: docker images

    - name: Tagging latest
      run: docker tag seeun0210/ahwhew-be-https:$(date +%s) seeun0210/ahwhew-be-https:latest

    - name: Push latest tag
      run: docker push seeun0210/ahwhew-be-https:latest
